# docker-compose.yml
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d library']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  app:
    build: .
    ports:
      - '8000:5000'
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: 'postgresql://postgres:admin@db:5432/library?schema=public'

volumes:
  pgdata:
