name: CI/CD Pipeline

on:
  push:
  
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
 
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Prisma Generate
        run: pnpm prisma generate

      - name: Build project
        env:
          DATABASE_URL: postgresql://postgres:admin@localhost:5432/library?schema=public
  
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: pnpm run build

      - name: Create temporary .env file
        run: |
          echo "DATABASE_URL=postgresql://postgres:admin@db:5432/library?schema=public" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PORT=5000" >> .env

      - name: Run Docker Compose Test
  
        run: docker compose up --build -d

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true

          tags: devrakib1248/library-server:latest
